### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by helloworld12305** [manjunathlokesh/Client-Server-model#1]
info is not displaying at server after adding contact can you please check it

**Comment by manjunathlokesh** [comment]
> info is not displaying at server after adding contact can you please check it
> 

Thank you for finding the bug I'll resolve it.

**Comment by helloworld12305** [comment]
Thanks

**Comment by manjunathlokesh** [comment]
Can you explain to me further like when you are exactly not able to see the info? 
**constraints to be aware is that**
1. server should be running if you want to see the live data update.
2. once your os reboots data that is stored will be erased.

**Comment by helloworld12305** [comment]
in server side program is not executing after accept system call
after running the client message is sending but server is not taking that

**Comment by manjunathlokesh** [comment]
Is it happening from the starting of the server or sometimes?

**Comment by manjunathlokesh** [comment]
I just cloned the code and tried and it's displaying. you can also paste screen shoot if required Thanks!!

**Comment by helloworld12305** [comment]
![Screenshot_2022-12-03_10_31_00](https://user-images.githubusercontent.com/95515203/205449013-11c81e07-e1f4-4689-a385-795a5c8446b2.png)
![Screenshot_2022-12-03_10_31_16](https://user-images.githubusercontent.com/95515203/205449015-da312ef2-c46d-4122-94a7-b40d7444a4f2.png)
see these screenshots once

**Comment by manjunathlokesh** [comment]
I think there is a problem with shared memory access on the server side as it's not giving a success message to the client and not displaying the saved data in the server side.

**Comment by manjunathlokesh** [comment]
You are on kali linux vm right?

**Comment by helloworld12305** [comment]
yes,its kali vm

**Comment by manjunathlokesh** [comment]
Let me check with another Ubunto distro

**Comment by helloworld12305** [comment]
okay please update your mail id in your profile, its showing address not found

**Comment by manjunathlokesh** [comment]
Sorry for that. Just updated my mail id.

**Comment by manjunathlokesh** [comment]
Hi there is a problem with semaphore object which is happening other than my machine that needs to be debugged. ill revert semaphore changes and you can use it for now.

**Comment by helloworld12305** [comment]
okay thanks!

**Comment by manjunathlokesh** [comment]
Hi @helloworld12305 please clone/download the code and try it now, I have reverted the semaphore changes. let me know if any thing is there.

**Comment by helloworld12305** [comment]
yeah now its working fine,thanks much:)

**Comment by helloworld12305** [comment]
can i get some help like how to send two formats of data like contact data and school data

**Comment by manjunathlokesh** [comment]
Can we take this as a new issue as it's out of the current scope of the bug? I have sent out a mail regarding this.

**Comment by helloworld12305** [comment]
sure
